APP_TITLE = "KOA Analytics V4.2 — Puntualidad y mapa estratégico"
DEFAULT_FILE = "Dinamica_de_paraderos_KOA_ES.xlsx"
DATA_SHEET = "seguimiento_h_op"

COL_DATE = "DIA DEL SERVICIO"
COL_ROUTE = "RECORRIDO"
COL_SHIFT = "JORNADA"
COL_SCHEDULED = "HORARIO-P1-REAL DE INICIO"
COL_ACTUAL = "Hora de inicio R1P1"
COL_USERS = "usuarios"
COL_STOPS = "PARADAS"
COL_EFFECTIVE_TIME = "Tiempo REAL con gabela de espera"

VALID_SHIFTS = ["MAÑANA", "TARDE"]
VALID_ROUTES = ["R1", "R2", "R3"]
OFFICIAL_STOPS = {
    "MAÑANA": ["OXXO HÉROES"],
    "TARDE": ["VIRREY", "HÉROES", "POLO"],
}
NON_EFFECTIVE_STOP_LABELS = {
    "NO SALIERON USUARIOS",
    "NO SE ALCANZO A REALIZAR RECORRIDO-CONGESTIÓN VH.",
    "NO SE ALCANZO A REALIZAR RECORRIDO-CONGESTION VH.",
}
